# Generated by Django 6.0.7 on 2026-08-09 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_genre_movie_language_movie_popularity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='movies.movie'),
        ),
    ]
