# Generated by Django 6.0.7 on 2026-08-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_booking_booking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='theater',
            name='screen',
            field=models.CharField(default='Screen 1', max_length=50),
        ),
    ]
