# Generated by Django 6.0.7 on 2026-08-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_movie_trailer_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='age_certification',
            field=models.CharField(default='U', max_length=10),
        ),
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.PositiveIntegerField(default=120, help_text='Duration in minutes'),
        ),
    ]
