# Generated by Django 6.0.7 on 2026-08-19 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_alter_payment_booking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='reserved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_seats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seat',
            name='reserved_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seat',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('booked', 'Booked')], default='available', max_length=20),
        ),
        migrations.AddIndex(
            model_name='seat',
            index=models.Index(fields=['theater', 'status'], name='movies_seat_theater_741728_idx'),
        ),
        migrations.AddIndex(
            model_name='seat',
            index=models.Index(fields=['reserved_until'], name='movies_seat_reserve_15b4e0_idx'),
        ),
    ]
