# Generated by Django 6.0.7 on 2026-08-20 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_seat_reserved_by_seat_reserved_until_seat_status_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='seat',
            name='movies_seat_theater_741728_idx',
        ),
        migrations.RemoveIndex(
            model_name='seat',
            name='movies_seat_reserve_15b4e0_idx',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='is_booked',
        ),
    ]
