# Generated by Django 6.0.7 on 2026-09-03 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_alter_booking_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='ticket_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
